import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/navbar";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
        />
      </head>

      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {/* Entire site container */}
          <div className="min-h-screen w-full flex flex-col relative">
            {/* Background grid */}
            <div
              className="absolute inset-2 opacity-25 blur-[0.5px] -z-10"
              style={{
                backgroundImage: `
                  linear-gradient(to right, #c4b9b9ff 1px, transparent 1px),
                  linear-gradient(to bottom, #c3c3daff 1px, transparent 1px)
                `,
                backgroundSize: "40px 50px",
                WebkitMaskImage:
                  "radial-gradient(ellipse 90% 40% at 50% 0%, #d8c6c6ff 60%, transparent 100%)",
                maskImage:
                  "radial-gradient(ellipse 90% 40% at 50% 0%, #f4eaeaff 60%, transparent 100%)",
              }}
            />
            <Navbar />
            <main className="flex-1 mt-5 p-2">{children}</main>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
